targets:
  $default:
    builders:
      json_serializable:
        options:
          create_factory: true
          create_to_json: true
          explicit_to_json: true
      freezed:
        options:
          union_key: type
          format: true
          copy_with: true
          map: true
          when:
            when: true
            maybe_when: true
            when_or_null: true
