name: flavor_builder
description: "Generate any file related to flavors in flutter"
version: 0.1.0
homepage: https://github.com/masreplay/flavor_builder
repository: https://github.com/masreplay/flavor_builder
issue_tracker: https://github.com/masreplay/flavor_builder/issues
documentation: https://pub.dev/documentation/flavor_builder/latest/
funding: [https://github.com/sponsors/masreplay]
topics: [flavor, flavorizr, flutter-native-splash, builder, generation]

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.4
  json2yaml: ^3.0.1
  json_annotation: ^4.9.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
