name: flavor_builder
description: "Generate any file related to flavors in flutter"
version: 0.1.3
homepage: https://github.com/masreplay/flavor_builder
repository: https://github.com/masreplay/flavor_builder
issue_tracker: https://github.com/masreplay/flavor_builder/issues
documentation: https://pub.dev/documentation/flavor_builder/latest/
funding: [https://github.com/sponsors/masreplay]
topics: [flavor, flavorizr, flutter-native-splash, builder, generation]

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  freezed_annotation: ^3.0.0
  json2yaml: ^3.0.1
  json_annotation: ^4.9.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4
