name: flavor_builder
description: "A new Flutter package project."
version: 0.0.1
homepage: 

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json2yaml: ^3.0.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:

scripts:
  g: fvm dart run build_runner build --delete-conflicting-outputs
